### ISSUE TITLE
`astartectl interfaces sync` should use the synchronous version of the API call

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astartectl#192]
Right now it's using the async version, and sometimes this leads to (silent) failure in the installation of some interfaces

**Comment by rafiramadhana** [comment]
@rbino Hi, I am interested with this issue.

Would you mind to point out which files that need to be updated?

Then, what does the term `silent failure` means here? How can I detect that? (maybe from logs?)

**Comment by matt-mazzucato** [comment]
Hello @rafiramadhana ,

to address this issue you should change the `realm_management.go` file within the [`astarte-go`](github.com/astarte-platform/astarte-go) repository. 

In particular the following functions must be updated:
- [`InstallInterface`](https://github.com/astarte-platform/astarte-go/blob/master/client/realm_management.go#L121)
- [`UpdateInterface`](https://github.com/astarte-platform/astarte-go/blob/master/client/realm_management.go#L182) 

Under the hood, when `sync`ing interfaces, astartectl will call the astarte-go's install and update functions (as you can see [here](https://github.com/astarte-platform/astartectl/blob/release-22.11/cmd/realm/interfaces.go#L264)).
The signature of these functions should be changed to receive also a bool value (stating if the call is asynchronous or not). The bool value is equal to the async parameter.

To implement the synchronous behavior, the  "async=false" query must be set when performing HTTP requests (check the [Astarte reference API](https://docs.astarte-platform.org/1.0/api/index.html?urls.primaryName=Realm%20Management%20API#/) if you need more context).
To get a rough idea of what we'd expect, you can have a look at [here](https://github.com/astarte-platform/astarte-go/blob/62761dbc87f286bd672c3c9747fcac2d7da760dc/client/appengine_device_paginator.go#L99-L105).
 
In order to test your changes to astarte-go in astartectl, you can add the following line at the end of the astartectl go.mod file (see [here](https://go.dev/ref/mod#go-mod-file-replace) for more info):
replace github.com/astarte-platform/astarte-go v0.90.5-0.20230323110518-62761dbc87f2 => /path/to/your/local/astarte-go

It should be enough to get you started. 
Looking forward to your contribution :smiley:

**Comment by rafiramadhana** [comment]
@matt-mazzucato 

Thanks for the explanation.

I've created a draft MR in astarte-go, would you mind to take a look https://github.com/astarte-platform/astarte-go/pull/48? Thanks.

**Comment by matt-mazzucato** [comment]
Closed by #201, which leverages astarte-platform/astarte-go#48.
Thanks to @rafiramadhana for the contribution!
